### ISSUE TITLE
Issue after upgrading to 1.0.4

### ISSUE THREAD

**Issue by dougg0k** [esetnik/customize-cra-react-refresh#13]
Failed to compile.

```
multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/src/runtime/ReactRefreshEntry.js ./node_modules/react-dev-utils/webpackHotDevClient.js .
Module not found: Can't resolve '/own_projects/project-name' in '/own_projects/project-name'
```

I also tried removing `node_modules` and `package-lock.json`, and the issue are still there.

**Comment by esetnik** [comment]
Please provide a sample project so I can reproduce.

**Comment by dougg0k** [comment]
I think it's just the version 1.0.4, it was working with 1.0.1 and I just tried 1.0.3 and it's working.

**Comment by esetnik** [comment]
The 1.0.4 version is improved and matches what react-scripts actually does to enable react refresh in the next release version. I am using 1.0.4 without any issues in my projects so if you need more help I will need to see a reproducible example so I can understand what’s going wrong.

**Comment by dougg0k** [comment]
Here you go, using the latest CRA version with a typescript template and followed the instructions in your README.md

https://github.com/dougg0k/cra-react-refresh-reproduce

**Comment by dariocravero** [comment]
I narrowed it down to an issue with `overrideEntry`, if you comment out this line `config.entry = paths.appPath` it works https://github.com/esetnik/customize-cra-react-refresh/blob/master/index.js#L9 - is the override needed?

**Comment by esetnik** [comment]
@dariocravero I am not able to install dependencies in the example project you provided. Looks like there's something wrong with the `package-lock.json`. Can you check it out?

```
~/work/cra-react-refresh-reproduce master
❯ npm i

> fsevents@1.2.13 install /Users/ethan/work/cra-react-refresh-reproduce/node_modules/jest-haste-map/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/ethan/work/cra-react-refresh-reproduce/node_modules/jest-haste-map/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ethan/work/cra-react-refresh-reproduce/node_modules/jest-haste-map/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ethan/.nvm/versions/node/v12.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/ethan/.nvm/versions/node/v12.17.0/bin/node" "/Users/ethan/.nvm/versions/node/v12.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ethan/work/cra-react-refresh-reproduce/node_modules/jest-haste-map/node_modules/fsevents
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> fsevents@1.2.13 install /Users/ethan/work/cra-react-refresh-reproduce/node_modules/watchpack-chokidar2/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/ethan/work/cra-react-refresh-reproduce/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ethan/work/cra-react-refresh-reproduce/node_modules/watchpack-chokidar2/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ethan/.nvm/versions/node/v12.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/ethan/.nvm/versions/node/v12.17.0/bin/node" "/Users/ethan/.nvm/versions/node/v12.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ethan/work/cra-react-refresh-reproduce/node_modules/watchpack-chokidar2/node_modules/fsevents
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> fsevents@1.2.13 install /Users/ethan/work/cra-react-refresh-reproduce/node_modules/webpack-dev-server/node_modules/fsevents
> node install.js

internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'nan'
Require stack:
- /Users/ethan/work/cra-react-refresh-reproduce/node_modules/webpack-dev-server/node_modules/fsevents/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at [eval]:1:1
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ethan/work/cra-react-refresh-reproduce/node_modules/webpack-dev-server/node_modules/fsevents/[eval]'
  ]
}
gyp: Call to 'node -e "require('nan')"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/ethan/.nvm/versions/node/v12.17.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.5.0
gyp ERR! command "/Users/ethan/.nvm/versions/node/v12.17.0/bin/node" "/Users/ethan/.nvm/versions/node/v12.17.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ethan/work/cra-react-refresh-reproduce/node_modules/webpack-dev-server/node_modules/fsevents
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok

> core-js@2.6.11 postinstall /Users/ethan/work/cra-react-refresh-reproduce/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js@3.6.5 postinstall /Users/ethan/work/cra-react-refresh-reproduce/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall /Users/ethan/work/cra-react-refresh-reproduce/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

added 1678 packages from 816 contributors and audited 1680 packages in 15.513s

59 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by esetnik** [comment]
@dougg0k thanks for the sample project. Can you try it with #14 and let me know if this solves the issue for you?

**Comment by RichardLindhout** [comment]
I have the same problem. Trying out master now.

**Comment by RichardLindhout** [comment]
Master works perfect! Thank you for this <3!!

**Comment by dougg0k** [comment]
@esetnik It's working. Thanks!

**Comment by esetnik** [comment]
Thanks for your patience and the reproduction. I have released [v1.0.5](https://github.com/esetnik/customize-cra-react-refresh/releases/tag/v1.0.5) with the changes.
